name: Scraper de Becas

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
     

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Verificar modelo en scraper.py
        run: grep "gemini" scraper.py

      - name: Correr scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python scraper.py
